# Generated by Django 5.2.17 on 2026-09-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structuretimers", "0010_alter_general_options_reconcampaign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconcampaign",
            name="gates_status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("pending", "Importing"),
                    ("failed", "Import failed"),
                ],
                default="ready",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="reconcampaign",
            name="import_status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("pending", "Importing"),
                    ("failed", "Import failed"),
                ],
                default="ready",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="reconcampaign",
            name="region_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
