# Generated by Django 5.2.17 on 2026-09-24 18:39

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
import structuretimers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structuretimers", "0011_reconcampaign_gates_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordTimerboard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "channel_id",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9]{1,20}$", "Enter a Discord channel ID."
                            )
                        ],
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "include_unflagged",
                    models.BooleanField(
                        default=True,
                        help_text="Also post timers without the Discord timerboard flag.",
                    ),
                ),
                (
                    "timer_types",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("NO", "Unspecified"),
                            ("AR", "Armor"),
                            ("HL", "Hull"),
                            ("FI", "Final"),
                            ("AN", "Anchoring"),
                            ("UA", "Unanchoring"),
                            ("MM", "Moon Mining"),
                            ("TF", "Theft"),
                        ],
                        default=structuretimers.models.default_timerboard_types,
                        help_text="Only selected types are posted. Preliminary timers are always excluded.",
                        max_length=23,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="timer",
            name="discord_timerboard",
            field=models.BooleanField(
                default=False,
                help_text="Include this timer on flag-only Discord timerboards.",
            ),
        ),
        migrations.CreateModel(
            name="DiscordTimerboardMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("channel_id", models.CharField(max_length=20)),
                ("message_id", models.CharField(max_length=20)),
                ("position", models.PositiveIntegerField()),
                ("content", models.TextField()),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="structuretimers.discordtimerboard",
                    ),
                ),
            ],
            options={
                "ordering": ("position", "pk"),
            },
        ),
    ]
