# Generated by Django 5.2.18 on 2026-10-10 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("structuretimers", "0015_rename_vulnerability_windows_label"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MapFleetToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_id", models.PositiveIntegerField(db_index=True)),
                ("alliance_name", models.CharField(blank=True, max_length=200)),
                ("alliance_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ship_name", models.CharField(blank=True, max_length=200)),
                ("ship_id", models.PositiveIntegerField(blank=True, null=True)),
                ("dps", models.PositiveIntegerField(blank=True, null=True)),
                ("logi", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "mobility",
                    models.CharField(
                        choices=[
                            ("super", "Super range"),
                            ("carrier", "Carrier"),
                            ("conduit", "Conduit carrier"),
                            ("blops", "Blops"),
                            ("gate", "Gate"),
                        ],
                        default="gate",
                        max_length=20,
                    ),
                ),
                (
                    "stance",
                    models.CharField(
                        choices=[("friend", "Friend"), ("foe", "Foe")],
                        default="foe",
                        max_length=10,
                    ),
                ),
                ("dscan", models.TextField(blank=True, max_length=50000)),
                ("note", models.TextField(blank=True, max_length=5000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MapTimerState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("events", models.JSONField(default=list)),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "timer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="map_state",
                        to="structuretimers.timer",
                    ),
                ),
            ],
        ),
    ]
