# Generated by Django 5.2.18 on 2026-10-10 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structuretimers', '0017_recon_member_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='database_entry',
            field=models.ForeignKey(blank=True, help_text='Database record of the structure this timer belongs to', limit_choices_to={'timer_type': 'PL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timers', to='structuretimers.timer'),
        ),
    ]
