# Generated by Django 5.2.18 on 2026-10-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structuretimers', '0019_link_timers_to_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='structures_structure_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='ID of the aa-structures structure this timer belongs to, used instead of a Database record when that app is installed', null=True),
        ),
    ]
