# Generated by Django 5.2.18 on 2026-10-10 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


PRELIMINARY = "PL"
# Fields that a Database record keeps, named the same on Timer and Structure.
FIELDS = (
    "reinforcement_time",
    "details_notes",
    "eve_alliance_id",
    "eve_character_id",
    "eve_corporation_id",
    "eve_solar_system_id",
    "is_opsec",
    "location_details",
    "objective",
    "owner_corporation_id",
    "owner_name",
    "structure_type_id",
    "structure_name",
    "user_id",
    "visibility",
)


def move_records_to_structures(apps, schema_editor):
    """Turn every Database record (an undated "preliminary" timer) into a
    Structure, keep its distances, and point its timers at it.
    """
    Timer = apps.get_model("structuretimers", "Timer")
    Structure = apps.get_model("structuretimers", "Structure")
    DistancesFromStaging = apps.get_model("structuretimers", "DistancesFromStaging")
    StructureDistance = apps.get_model("structuretimers", "StructureDistance")
    for record in Timer.objects.filter(timer_type=PRELIMINARY).iterator():
        structure = Structure.objects.create(
            **{field: getattr(record, field) for field in FIELDS}
        )
        # Keep how fresh the recon is, instead of "now".
        Structure.objects.filter(pk=structure.pk).update(
            last_updated_at=record.last_updated_at
        )
        StructureDistance.objects.bulk_create(
            [
                StructureDistance(
                    structure_id=structure.pk,
                    staging_system_id=distance.staging_system_id,
                    light_years=distance.light_years,
                    jumps=distance.jumps,
                )
                for distance in DistancesFromStaging.objects.filter(timer=record)
            ]
        )
        Timer.objects.filter(database_entry=record).update(structure=structure)
        record.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0025_remove_evecharacter_last_updated_and_more'),
        ('eveuniverse', '0012_alter_evebloodline_eve_ship_type'),
        ('structuretimers', '0022_standings_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reinforcement_time', models.TimeField(blank=True, null=True, verbose_name='Vulnerability windows')),
                ('details_notes', models.TextField(blank=True, default='', help_text='Notes with additional information about this timer')),
                ('is_opsec', models.BooleanField(db_index=True, default=False, help_text='Limit access to users with OPSEC clearance. Can be combined with visibility.')),
                ('location_details', models.CharField(blank=True, default='', help_text='Additional information about the location of this structure, e.g. name of nearby planet / moon / gate', max_length=254)),
                ('objective', models.CharField(choices=[('UN', 'undefined'), ('HO', 'hostile'), ('FR', 'friendly'), ('NE', 'neutral')], default='UN', max_length=2)),
                ('owner_name', models.CharField(blank=True, default=None, help_text='Name of the corporation owning the structure', max_length=254, null=True)),
                ('structure_name', models.CharField(blank=True, default='', max_length=254)),
                ('visibility', models.CharField(choices=[('UN', 'unrestricted'), ('AL', 'Alliance only'), ('CO', 'Corporation only')], db_index=True, default='UN', help_text='The visibility of this timer can be limited to members of your organization', max_length=2)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('fitting', models.TextField(blank=True, default='', help_text='Fitting of the structure, e.g. copied from EVE')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('eve_alliance', models.ForeignKey(blank=True, default=None, help_text='Alliance of the user who created this timer', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='eveonline.eveallianceinfo')),
                ('eve_character', models.ForeignKey(blank=True, default=None, help_text='Main character of the user who created this timer', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='eveonline.evecharacter')),
                ('eve_corporation', models.ForeignKey(blank=True, default=None, help_text='Corporation of the user who created this timer', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='eveonline.evecorporationinfo')),
                ('eve_solar_system', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eveuniverse.evesolarsystem')),
                ('owner_corporation', models.ForeignKey(blank=True, help_text='Player corporation owning the structure', limit_choices_to={'category': 'corporation'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='structuretimers.organization')),
                ('structure_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eveuniverse.evetype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='timer',
            name='structure',
            field=models.ForeignKey(blank=True, help_text='Database record of the structure this timer belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timers', to='structuretimers.structure'),
        ),
        migrations.CreateModel(
            name='StructureDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_years', models.FloatField(blank=True, default=None, null=True)),
                ('jumps', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staging_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_distances', to='structuretimers.stagingsystem')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='structuretimers.structure')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('structure', 'staging_system'), name='fpk_structure_distances_from_staging')],
            },
        ),
        migrations.RunPython(move_records_to_structures, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='timer',
            name='database_entry',
        ),
    ]
